#数据库
Mysql:
  #驱动
  dbDriver: 'com.mysql.jdbc.Driver'
  #连接地址
  dbURL: 'jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT'
  #MySQL数据库用户名
  userName: 'root'
  #MySQL数据库密码
  password: '1234'
DragonGuild:
  #插件消息前缀
  prefix: '[公会]'
  #创建公会花费金币
  cost: '10'
  #修改公会花费金币
  update_cost: '10'
  #每个成员在线一小时增加公会经验
  exp: '10'
  #等级:升级所需经验:最大成员数
  level:
    - '1:0:10'
    - '2:10:20'
    - '3:20:30'
    - '4:50:40'
    - '5:100:50'
    - '6:150:60'
    - '7:300:70'
    - '8:500:80'
    - '9:800:90'
    - '10:1500:100'