#数据库
ActivationCode: "123"
Mysql:
  #驱动
  dbDriver: 'com.mysql.jdbc.Driver'
  #连接地址
  dbURL: 'jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT'
  #MySQL数据库用户名
  userName: 'root'
  #MySQL数据库密码
  password: '1234'
#快捷键
hotkeys: "G"
DragonGuild:
  #插件消息前缀
  prefix: '[公会]'
  #无公会时展示
  noteam: '[龙之公会]'
  #创建公会花费金币
  cost: '10'
  #修改公会花费金币
  update_cost: '10'
  #每个成员在线一小时增加公会经验
  exp: '10'
  #等级:升级所需经验:最大成员数
  position:
   chairman:
     name: '会长'
     permission:
       #踢人
       kick: true
       #修改公会名字
       updateGuildName: true
       #编辑公告
       editNotice: true
       #审批
       apply: true
       #任职
       appoint: true
       command:
         - 'server:say @ 创建了公会%dragonguild_name%'  #service:代表服务器发出指令,@代表事件涉及的玩家名字,%dragonguild_name%是公会名字变量
         - 'player:say 我是会长啦' #player:代表由事件玩家发出指令
         - 'judge:%player_level% > 0 && %player_health% > 5:5' #judge:是条件判断语句,&&是逻辑运算符,代表且.翻译:如果玩家等级大于0,并且生命值大于5,执行第5行语句
         - 'judge:%player_level% > 10 || %player_health% = 20:6' #||是逻辑运算符,代表或,翻译:如果玩家等级大于10,或者生命值等于20,执行第6行语句
         - 'player:say 我是第5行'
         - 'player:say 我是第6行'
         - 'judge:%dragonguild_is_creator% = "是":8' #翻译:如果玩家是会长,执行第8行语句
         - 'player:say 我是第8行'
   vice_chairman:
     name: '副会长'
     permission:
       #踢人
       kick: true
       #修改公会名字
       updateGuildName: true
       #编辑公告
       editNotice: true
       #审批
       apply: true
       #任职
       appoint: true
     command:
       - 'tp'
       - 'fly'
   veteran:
     name: '元老'
     permission:
       #踢人
       kick: true
       #编辑公告
       editNotice: true
       #审批
       apply: true
     command:
       - 'tp'
       - 'fly'
   god_of_war:
     name: '战神'
     permission:
       #审批
       apply: true
     command:
       - 'tp'
       - 'fly'
   elite:
     name: '精英'
     command:
       - 'tp'
       - 'fly'
   ordinary:
     name: '普通成员'
     command:
       - 'tp'
       - 'fly'

  #事件系统
  event:
    memberjoin:
      - 'player:say 我加入公会啦'
    memberOut:
      - 'tp'
      - 'fly'
  level:
    - '1:0:10'
    - '2:10:20'
    - '3:20:30'
    - '4:50:40'
    - '5:100:50'
    - '6:150:60'
    - '7:300:70'
    - '8:500:80'
    - '9:800:90'
    - '10:1500:100'

  information:
    name: '游戏名：'
    contribution: '贡献：'
    level: '等级：'
    member: '成员：'