name: DragonGuild
main: com.suixin.dragonguild.DragonGuild
version: ${project.version}
authors:
- suixin
softdepend:
- VaultAPI
- DragonCore
commands:
  gh:
    description: 游戏指令
    usage: /gh
permissions:
  dragonguild.gh:
    description: Allows you to use gh